# Site settings
title: Bare Minimum
description: > # this means to ignore newlines until "baseurl:"
  The smallest possible quantity or the least fulfilling, but still adequate, condition that is required, acceptable, or suitable for some purpose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artrei.github.io" # the base hostname & protocol for your site
github_username:  artrei

# Build settings
markdown: kramdown
